---
title: "Dealing with past failures"
author: "Joram Mutenge"
date: "2024-06-05"
---

You can deal with your past failures in two ways. You can either wallow in regret, reminiscing about what might have been if you had taken that chance or hadn't done that. Or you can leverage those failures to build a better version of yourself.

Unless you want to be a failure for the rest of your life, you'll agree that leveraging your failures is a smarter approach.

What does it really mean to leverage your past failures? Think about the first time you had a crush on someone and how you messed up your attempt to let them know you were madly interested in them.

Yes, it was a failure because you didn't end up being with that person. But you also didn't spend the rest of your life complaining about that failure. You went ahead and pursued other people.

In this situation, leveraging your failure would mean that in addition to not complaining about the bad outcome, you extract useful lessons from it to approach future opportunities differently.

>I believe you can lessons from every situation in life no matter how trivial. You only need to be vigilant enough to see those lessons.

I always leverage my failures because they help me become a better version of myself. That’s not to say I delight in my failures. I'm on Elon Musk’s side when he said that.

>Failure has its lessons, but I would rather learn from success.

Like many people, it pisses me off when a plan doesn't go my way. However, I don't focus on the anger. Instead, I focus on the things I did badly to avoid them and consider things I didn't do so I can do them should a similar opportunity present itself later.

Wallowing in regret over past failures is the surest way to becoming a failure for the rest of your life. Be smart and extract lessons from your past failures!