---
title: 'How I fell in love with the semi-colon'
author: '{{< var author >}}'
date: '2024-06-24'
---

It's perhaps the most underused punctuation in the English language; the semi-colon has fallen out of favor. Fewer and fewer people use it mainly because most people don’t know how to correctly use it.

My love affair with the semi-colon started when I was a junior in college. It was then that my frequent use of it began. What spurred it was a quote by Mark Twain I had stumbled upon. It said:

> A semi colon is the most useless piece of punctuation. It only shows that you've been to college.

That last part got me. Being in college, I wanted to prove that I was an outstanding student, and using the semi-colon was my way of doing it. Thus, my love affair with this obscure punctuation mark began.

By the way, did you know that the semi-colon was invented in the Renaissance? It first appeared in 1494, in a book published in Venice by Aldus Manutius called *De Aetna*.

The semi-colon is a hybrid between a comma and a colon, and its purpose is to prolong a pause or create a more distinct separation between parts of a sentence.

Now that you know this, you can start using the semi-colon correctly and show that you’ve been to college*;* it doesn’t matter if you never went to college. See what I did there?

Here's another example of the correct use of the semi-colon from my favorite novel, *This Side of Paradise*:

> She fed him sections of the “Fetes Galantes” before he was ten; at eleven he could talk glibly, if rather reminiscently, of Brahms and Mozart and Beethoven.

From junior year until I graduated college, I included at least two semi-colons in every paper I wrote, that’s how much I loved this rare punctuation mark!

When was the last time you used a semi-colon? Did you use it correctly? Email me; I’d love to know!