---
title: "Create your own dream"
author: "Joram Mutenge"
date: "2024-06-11"
---

There is no limit to how much you can dream, yet other people still want to lump themselves with other people's dreams.

The problem with being the person who piggybacks on someone else's dream is that you have no control. The owner of the dream has total control and is the driver; you're just a passenger in that dream.

If the dream materializes, you get some of the benefits. If it falls apart, you lose everything. That's why it's important to be the architect of your dream and work towards making it a reality.

It's OK to seek other people's help as you work towards your dream, but you must completely control it.

> Success will always be unattainable if you allow others to take control of your dreams.

When someone has total control of your dream, they can kill it easily, or worse off, they can steal it.

Your dreams are a treasure and they deserve to be treated with as much care as you'd treat your hard-earned cash.