---
title: "Do they know they're competing with everyone in the world?"
author: '{{< var author >}}'
date: '2025-01-03'
---

I haven't lived in Zambia for many years now, but I grew up there. That’s why I feel a deep sense of connection to the circumstances of young people there, particularly students.  

When I was a child attending school in Zambia, it was considered a great achievement to rank first in your class—to be at the top. Your competitors were your classmates, and all you needed to do was produce better test results than they did to be the best.  

However, today, competition is no longer local but global. Thomas Friedman reminds us in his book, *The World Is Flat*, that the playing field is now level on a global scale. If you’re a high school student, your competition is not limited to the students at your school but extends to every high schooler in the world. Similarly, if you’re in college, you’re not just competing with students at your institution but with students at every college across the globe.  

I fear that many young Zambians don’t realize they are competing with the world. As the world converges into a global village, it is no longer enough to be the best at your school or in your district. You must aim to excel at a global level.  

The 21st century has witnessed a surge in knowledge work, where many jobs can now be done remotely. A software engineering or data analyst position in the USA is not just being pursued by Americans—it’s also being sought after by people from Cambodia, Nigeria, South Africa, and countless other countries. Once again, competition is no longer local; it is global.  

To succeed in this competitive world, you must understand this fundamental truth:

> Local competition is dead. Global competition is the present and the future.