---
title: "The smartest dumb kid in a dumb class"
author: '{{< var author >}}'
date: '2025-01-26'
---

I grew up in a shanty compound and went to primary school in the ghetto. Most of the kids at my primary school were not book smart. They didn't care about education and were only there because their parents wanted them to be.

While there, I thought I was a smart kid because I was always at the top of the class. However, when I was selected to attend a prestigious Catholic school for 8th grade, I met kids who were truly smart. My erroneous belief that I was smart was quickly corrected, and the truth was revealed:

> I was the smartest dumb kid in a dumb class.

The kids at this Catholic school were intelligent, well-spoken, and knowledgeable about the world. I felt like an imposter who had no business being there. At one point, I even considered leaving the school because I missed the feeling of being considered the "smartest kid."

However, instead of giving in to despair, I saw this as a challenge to better myself. I started studying hard to reach the level of the other kids at my new school. Within a few months, I managed to catch up.

When you're surrounded by unsuccessful people, your meager success may seem extraordinary. It's only when you're exposed to people who are more successful that you realize you're not as accomplished as you thought.

> The best hack to improve yourself is to surround yourself with people better than you.

The problem is that most of us despise the feeling of not being the best. That's why so many people choose to spend time with others who praise them for being the best in the group.

> If you want to improve yourself, you need to step out of your comfort zone and seek new challenges. Your attempts to overcome those challenges will become the training ground for self-improvement.

In other words, if you want to be smart, surround yourself with smart people. If you want to be successful, surround yourself with successful people. If you want to be physically strong, surround yourself with people who hit the gym regularly.

However, you should be warned: this may not be a reliable recipe for internal happiness. Naval Ravikant once quipped:

> If you want to be unhappy, surround yourself with people more successful than you. If you want to be happy, surround yourself with people less successful than you.

The message here is that being surrounded by people more successful than you can leave you feeling inadequate. That feeling can be disheartening for many and may lead to unhappiness. But I encourage you to take advantage of that discomfort and use it as fuel to push yourself to become better.

On the other hand, when you're surrounded by people less successful than you, they will praise you for your achievements, boosting your ego. My fear is that this can delude you into thinking you’ve "made it," when in reality, you are just the smartest dumb kid in a dumb class.