---
title: "Envy is the most powerful source of motivation"
author: '{{< var author >}}'
date: 'August 09, 2025'
toc: true
toc-title: 'Sections'
toc-location: right
toc-depth: 3
categories: [essay]
---

Jealousy is not the same as envy, but most people treat them as if they are. The simplest way I can distinguish the two is: jealousy asks, *Why does it have to be him or her?* Envy, on the other hand, asks, *Why can't it be me?* This is a very important distinction.

The American writer Gore Vidal put it best when he said:

> Every time a friend of mine succeeds, a small part of me dies.

This is not a statement of jealousy; it's a statement of envy. Vidal dies inside because he realizes that, just like his friend, he had the capacity to succeed, but he didn’t.

Envy is a good reminder that you are sitting on untapped potential, and that you can be more than you are right now.

## Envy is greater with people closer to us

When I was growing up in Zambia, my dream was to study abroad. I would hear stories of a friend of a friend leaving for Russia, or some distant relative I had never met going to the UK to study. But these stories didn’t motivate me enough. Yes, I admired these people, but the question *Why can’t it be me?* never crossed my mind.

It wasn’t until a very close friend I met in eighth grade left Zambia to study abroad that I became envious. When I heard the news for the first time, a small part of me died, to borrow Vidal’s words.

I wasn’t jealous of my friend. I was envious of him. Suddenly, I realized that I too had the capacity. Suddenly, I realized that I had what it takes to study abroad. My friend was not some super genius. I was just as smart as he was. Realizing that made me think: *If he can do it, I can do it too.*

I used that envy as a source of motivation to follow through on my dream to study abroad, until it happened.

I’m writing this post far from my native Zambia. I’m somewhere in the United States -- or, to be more specific, somewhere in the Midwest.

Do not repress your envy. Be curious about the things you’re envious of. Envy gives you clues to what you should be or should be doing, but currently are not.

