---
title: "The older you grow, the smarter your parents become"
author: '{{< var author >}}'
date: '2025-05-12'
---

Yes, you read that title correctly. I know it sounds a bit weird. I thought so too when I first heard it from David Foster Wallace.

If you're unfamiliar with David Foster Wallace, I encourage you to look him up after reading this. For now, just know he was an a smart man. So when he said:

> The older you grow, the smarter your parents become,

I figured it was worth some reflection.

At first glance, the quote seems backwards. If anyone else had said it, I might've dismissed it entirely. But since it came from someone as smart as Wallace, I decided to give it more thought.

## Here's my interpretation of it

As a teenager trying to fit in or seem cool, it's easy to ignore your parents' advice. They seem out of touch -- from a bygone era. What could they possibly know about navigating *your* world? So you rebel and ignore their advice, eager to forge your own path.

This is common. Why? Because teenage brains lack wisdom which causes bad judgment. But as you grow into adulthood, experience life, and face its many challenges, your perspective changes. You begin to see things more clearly -- in many ways, through your parents' eyes.

Suddenly, the lessons they tried to teach you make more sense. The advice you once rolled your eyes at starts to feel relevant. Indeed your parents become smarter to *you* now that you've gained the wisdom to finally understand them.

## What does the quote mean to you?

David Foster Wallace didn't elaborate on the quote -- perhaps he assumed its meaning would speak for itself. And maybe it does for some. But for me, it took a little unpacking.

What about you? Does the quote mean something different to you? I'd love to hear your take. Honestly, I wouldn't be surprised if someone out there had a completely new interpretation I hadn't considered.