---
title: "Be clever when times are good"
author: '{{< var author >}}'
date: '2025-02-15'
---

Have you ever noticed that you almost always come to your senses when things go wrong? There's something about being in trouble—when things aren't going your way—that forces your brain to think critically and apply logic to the situation. Bad times have a way of making you recognize the errors in your ways.  

While realizing your mistakes during hard times is valuable, it's often too little, too late. You've probably heard the saying, "Every dog has its day." I'd like to expand on that:  

> If every dog has its day, a clever dog is one that seizes the day.  

Whenever I hear people reminiscing about the *good old days*, I know they're indirectly saying things aren't going well for them now. Sometimes, they even have a plan to reclaim those better days. But that's not being a clever dog.  

> A good plan executed too late is no better than a bad plan.  

Imagine how much better and richer your life would be if you gained the insights you usually have during tough times *while* things are still going well. The best time to plan for a better future is when you're at your peak—when you have the energy, resources, and freedom to act. When it's your day, you are unencumbered and free to execute your plan.  

Always be on the lookout for your good day, and make the most of it when it comes. When things are going your way, you have the power to change your life. That is precisely the moment to wake up and think about how to improve it.  

So, are you a clever dog?