---
title: "Don't wake up in the morning to be average"
author: "Joram Mutenge"
date: "2024-06-12"
categories: [book]
---

Every time you wake up in the morning, it's a whole new day. You can reinvent yourself into something good or something bad.

Each day brings a new type of energy into your life, and this energy is strongest in the morning. With it, you can do wonders.

This phenomenon isn't a secret, but it amazes me that fewer people know about it. It’s worth pointing out that it’s one thing to know about it and to harness and practise it is another.

Harnessing this new morning energy entails burying yesterday’s regrets and troubles — never allowing them to suck out this energy that comes with every new day.

Today has its problems. Don't make it worse by filling it up with yesterday's problems. Whenever you start a new day, you must see yourself as a new person with the power to bring out your best performance.

George Horace Lorimer's advice helps harness the energy of the new day. He said:

> You've got to get up every morning with determination if you're going to go to bed with satisfaction.

Avoid getting up in the morning to be average, because if you are average, you are invisible. And if you're invisible, opportunities pass you by.