---
title: "Five business questions you must answer"
subtitle: "To know if you're ready to start your own business"
author: "Joram Mutenge"
date: "2024-06-08"
categories: [business]
---

Having read several books about entrepreneurs and listened to many interviews about business founders, I've concluded that if you want to start and run a successful business, you must answer the following five questions.

First, let me point out that there are two ways to start a business. You can either find a solution to a problem people didn't know about and then make them aware, so they buy your solution. Or you can provide a solution to their complaints and charge them for it.

The latter is much easier than the former. When people know their problem, they’re more willing to pay for a solution that solves that problem. The people you have to convince that they have a problem are usually reluctant to pay for the solution you're offering.

So what are the five questions you must answer?

1 *What problem are you solving?* You must be clear about the problem you're trying to solve. Answering this question will also help you see whether the problem you're trying to solve is something people are frustrated about and are willing to do anything to get rid of, or if it’s a problem they can live with. You have to be clear and honest about that problem.

2 *How is your solution unique?* If you discover that the problem is something people already know about, chances are you’re not the only person trying to solve it. That's why you need to be clear about how unique your solution is. If you're merely copying an existing solution, don't expect people to abandon the person offering that solution and come to you. The only way that will happen is when you prove that you have a unique selling point (USP). Unique doesn't necessarily mean it has to be completely different. Your solution may be faster at solving the problem or require less effort. Remember when the penny farthing (the first bicycle) was invented? It had a big front wheel and a tiny back wheel. Yes, it solved transportation problems but later inventions with equal-sized wheels were better at solving that problem because they were efficient.

3 *How will you make money?* If you don't make money, you don't have a business. You must know how your business will make money before starting it. Will you sell the product or rent it? Will you have one or multiple revenue streams? If it’s multiple streams, are you ready to list them?

4 *Is the problem ready to be solved?* The last thing you want is to be too early in the game. Providing a solution to a problem that will take decades for people to embrace is pointless. There are some problems that people are happy to live with and so they never seek solutions for them. If you're going to run a successful business, the problem you're solving must be ready to be solved, i.e. the market should welcome your solution, otherwise you don't have a business.

5 *How will your business be sustainable?* We've all heard of one-hit wonders; businesses that show up today and tomorrow they're gone. You don't want your business to be a one-hit wonder. What you want is for your business to have returning customers. New customers are great, but retaining customers indicate that your product or service is so good that people will continue to buy it.

When you've answered these five questions, you can tap yourself on the shoulder and say, "I'm ready to run my own business."