---
title: 'A lesson every young career person should know'
author: '{{< var author >}}'
date: '2024-12-16'
categories: [career]
---

This is meant for people just starting their careers or holding junior positions. Navigating work life can be challenging, especially when you want to make an impact. We all want our hard work and accomplishments to be acknowledged and rewarded.

But most of the time, your hard work and accomplishments won't be acknowledged because everyone in the company is too busy focusing on their work and solving their own problems to notice what you're doing.

That's why it's important to highlight your accomplishments and talk about them. Do not work hard in silence. Make it visible to your manager that you're working hard and tell her about your accomplishments in the company. This is what it means to advocate for yourself.

Make it a habit to talk about the work you've done and how it is helping the company. When you do this, you show that you are valuable to the company. You also position yourself better for a promotion.

Remember:

> Your co-workers’ perspective of you is what matters.

If the people you work with perceive you as someone who is not valuable, it doesn't matter how hard you work, when the time for layoffs comes, you'll be the first to be let go.

Fortunately, you can control how people perceive you by:

> i.  Building a reputation as someone who gets things done.  
> ii. Making sure that your hard work is visible.  
> iii. Telling your co-workers, especially your manager, about your accomplishments.

If what matters most is how people perceive you, why not be intentional at shaping that perspective and make it a positive one.