---
title: "You shouldn't be punished forever for your mistake"
author: "Joram Mutenge"
date: "2024-05-30"
categories: [tv show]
---

We all make mistakes, which is good because we learn from them.

But sometimes, these mistakes can be so costly that we end up being punished for making them.

If, for example, you get drunk at a bar and end up cheating on your girlfriend, your punishment could be that she stops trusting you. 

Whenever your girlfriend sees you talking to other women, she'll always suspect that you're cheating, even when you're just engaging in a friendly conversation.

But even when you make the costliest mistakes, you shouldn't be punished for eternity.

I find comfort in this quote from the TV show *Single Ladies*, which says:

> You don't deserve to be punished for your mistakes forever.

As long as we're human, we're bound to make mistakes. Even Alexander Pope reminded us that “To err is human.”

Some mistakes may warrant punishment, but no mistake warrants eternal punishment.