---
title: "The two dimensions of authenticity"
author: '{{< var author >}}'
date: '2025-03-16'
---

Everyone working on a personal brand today claims to be authentic because it's fashionable to say you are. Authenticity is a buzzword, and everyone jumps on it, left and right. Don't get me wrong, I know it's great to be authentic and I like dealing with authentic people. However, I fear that many people today misunderstand what authenticity really is. And those who think they do, understand only part of it.

I'd argue that there are two dimensions to authenticity:

1. being true to yourself.
1. being what you say you are to others.

Today's message about authenticity shared by many influencers focuses on being true to yourself. Yes, it's good to accept who you are and live your life but it's more important to be the person you claim to be to other people. If, for example, you claim to be trustworthy but your actions prove otherwise, you're not being authentic.

> The best way to get people to work with you is to live up to your word.

It's hard enough to be successful, but it's even harder to do it all by yourself. When you work with others, you make your journey to success a little. Yes, be true to yourself, but more importantly, live up to who you say you are. That's the side of authenticity most people overlook.