---
title: 'Stand for something'
author: '{{< var author >}}'
date: '2024-07-19'
categories: [business]
---

In the olden days, you could run a business without worrying about building a brand. Today, having a brand is a requirement to run a successful business.

Consumers today pay attention to your brand more than they pay attention to your business. You should ensure that your business values are reflected in your brand -- and the best way to do that is to stand for something.

Not everyone has to agree with what you stand for. Your business can't be for everyone, but those who believe in it should know what to expect from your brand.

Nike is a good example of a brand that's not afraid to take a stand. When Nike released the ad that featured Colin Kaepernick, people were enraged and criticized the company. Some even went as far as burning Nike shoes. But Nike remained resolute because the stand it took reflected its values.

Gillette was also criticized for its ad *The Best Men Can Be*, but the company still stuck to its guns because the ad’s message reflected its values.

Most businesses today want to please everyone so they’re afraid to take a stand on something that may alienate some customers. But when you fail to take a stand on something, you confuse your loyal followers because they don't know where you stand on issues that matter to them. Remember:

> If you don't stand for something, you fall for everything.

This applies to people as much as to businesses because nowadays we are all personal brands.