---
title: 'Failing is not losing'
author: '{{< var author >}}'
date: '2024-07-05'
---

Let's face it, no one wakes up in the morning saying, "I'm looking forward to failing more today!" It just never happens. But even if we don't like it, failure has a way of finding its place in our lives.

> The best way to avoid failure  is to never try. Paradoxically, it's also the best way to stay stagnant.

Failure is universal but it sends different messages to people. Some see it as the ultimate indicator that they're a loser. Others take failure as a motivation boost. These people say, "Yes I've failed but next time I won't. I'll prepare more"

Because failure is inevitable, you should embrace it. Embracing failure doesn't mean loving it but using it as fuel to drive you. When you embrace failure you learn from it and become wiser.

Successful people hate failure too, but they understand its value. If you can't embrace failure, the possibility, or the tremendous fear of failure, you can't be wildly successful. Remember:

> Failing isn't losing. Stopping after after failing is losing.