---
title: "Loss aversion"
subtitle: "When the pain of losing is worse than the pleasure of winning"
author: "Joram Mutenge"
date: "2024-06-17"
---

Failure may be a stepping stone to success, but most people hate it. I do too. Sometimes failure can be so devastating that you don't know how to recover.

It doesn't surprise me that given a choice to learn a lesson from failure or success, most people would choose to learn that lesson from success. Yet we know that:

> A lesson learned the hard way has the virtue of never being forgotten.

The principle of loss evasion helps explain why most people despise failure. The principle states that people prefer avoiding losses to making equivalent gains. As Brad Pitt eloquently put it in *Moneyball*

> I hate losing more than I even wanna win.

We can all relate to Brad Pitt. It's no wonder most people don’t try out new things that can make them even more successful. They stick with the familiar because it's safe. But when we avoid failure, we reduce our chances of becoming successful.

Only by taking chances can you know how much you can achieve. Also, you value your winnings a lot more when you've had some losses along the way.