---
title: "The magic of small compounding"
author: '{{< var author >}}'
date: '2025-04-09'
---

> I fear not the man who has practiced ten thousand kicks once, but I fear the man who has practiced one kick ten thousand times.

I find this quote, attributed to Bruce Lee, very profound. Why? Because it touches on something incredibly powerful that most people overlook—consistency.

We often do many things at once, usually with less focus and minimal attention to detail. But doing the same thing repeatedly—and refining it along the way—is challenging. Mainly because it feels boring. After all, variety is the spice of life, or so they say. But to become truly good at something, you have to do it many times. Remember:

> Repetition is the key to mastery.

Doing one kick every day for ten thousand days requires discipline and consistency—and the skill and knowledge you gain compounds over time. Bruce Lee understood the value of small compounding. The skill developed from doing a little bit of something consistently over a long period is far greater than what you gain from doing it intensely over a short time.

Consider reading. Most people can finish a textbook in a day, but the information retained in that one sitting will be far less than what they would retain by reading smaller sections every day over a longer period.

Small changes may feel insignificant when you're just starting, but when you look back after a long time, those changes can be remarkably significant. Never underestimate the power of small compounding. Small, incremental improvements lead to bigger outcomes in the long run. Don't try to overdo things—instead, stay consistent with the small steps you take toward larger goals, and you'll get far more value out of them. Remember:

> The journey of a thousand steps begins with one step, but you have to keep walking.