---
title: 'Did you win the genetic lottery?'
author: '{{< var author >}}'
date: '2024-11-28'
categories: [essay]
---

If there were a perfect human, that human would do no wrong. But since we've all done wrong things knowingly or unknowingly, it follows that none of us is perfect. And it's okay not to be perfect until it isn't.

So what do I mean by winning the genetic lottery? Many would think I mean being born white, male, straight, or rich but I mean none of these things. What I mean is do you have defects that society overlooks or do you have defects that society frowns upon, or even worse wants to punish you for?

If none of us is perfect, then we're all lame somehow. Put another way, we all have defects that make us imperfect human beings. So, in answering the question in the title, I'll put the defects that we can all have into two categories:

1.  Defects that society perceives as acceptable.
2.  Defects that society perceives as unacceptable.

Having acceptable defects makes you the winner of the genetic lottery. Why? Because society isn't going to punish you for having those defects.

Suppose you were born with a lisp and have trouble pronouncing words with "s", society can ignore that defect in you and treat you as normal because your defect is acceptable. Similarly, if you were born with one eye, society can sympathize with you for having this defect. This is what it means to win the genetic lottery. It's having defects that society ignores or pities.

Or take the confession of C.S. Lewis, the man who wrote the wildly popular children’s book *The Chronicles of Narnia*

> I myself do not enjoy the society of small children . . . I recognize this as a defect in myself—just as a man may have to recognize that he is tone deaf or color blind.

Fortunately for Lewis, his peculiar trait is one society is willing to overlook—disliking the company of children isn't something he can be punished for. How ironic, though, that a celebrated children’s author doesn’t particularly enjoy spending time with kids!

By contrast, you know you've lost the genetic lottery when you have defects that society frowns upon. Sadly, unacceptable defects can be so bad that society chooses to punish anyone with those defects.

A good example of an unacceptable defect is being born with pedophilic tendencies. Imagine the torture people who are sexually aroused by children go through. Whenever they’re around kids, they constantly have to fight against their sexual impulses to not act on them. Even worse, they have to fight this battle for the rest of their natural life. If they act on their pedophilic tendencies, they risk going to jail.

Don't get me wrong, I'm not excusing pedophiles from their wrongdoing. Rather, I'm pointing out how tough a situation it is for pedophiles to have to constantly wrestle with their sexual urges whenever they're around kids. And even though the pedophiles deserve to be punished, it's not their fault that they were born with this defect that society deems unacceptable. They could've had any other innocent defect like being deaf or being an introvert and society would've been OK with it. Unfortunately, they lost the genetic lottery because their defect is punishable by law.

Another group of people who seem to have completely lost the genetic lottery are serial killers. I remember watching a documentary about the infamous serial killer Ted Bundy. From the outside, he seemed like a perfectly normal person, but he had a disability. Every so often he would have these urges to kill and these urges wouldn't go away until he succumbed to them and murdered someone. He once told his girlfriend that these urges to murder women were so overwhelming he couldn't control them. Relief only came after committing the murder.

Ted Bundy was an unlucky guy because his defect was hated (and rightly so) by society. Had he been given a choice; he wouldn't have selected to be born that way. But in the genetic lottery, no one chooses the defects they get. All you can hope for is that your defects are acceptable to society.

Coming back to our question, did you win the genetic lottery? It helps to rephrase the question this way: Do you suppress or hide your defects every day because if you show them, society will punish you for having them? Or do you let the world see your defects because society deems them acceptable? You, more than anyone else, know how imperfect you are. And if the world welcomes your imperfections, then you, my friend, should be grateful because you won the genetic lottery. If the world doesn't accept your imperfections, tough luck.