---
title: 'Ideas are a dime a dozen'
author: '{{< var author >}}'
date: '2024-07-11'
categories: [business]
---


Most people have business ideas, but few have businesses. People with only business ideas are convinced that what's standing in the way between their idea and it being a business is money. Even worse, they expect prototypes of their business to be funded.

Unfortunately, prototypes rarely get funding let alone ideas. You cannot think your way to entrepreneurship because it requires action. You must be bold and scrappy to turn your idea into a prototype with the little resources you have. To say that you need to finance a prototype is asking for too much. Turn your prototype into a simple yet finished product, then ask for money to scale up the finished product.

> Money isn't the key to unlocking the potential of the entrepreneur.

We don’t have a shortage of ideas. We have a of execution. The people who can execute their ideas are the ones who win.

Don't worry about starting small with your idea. Remember not everything big today started big.

> Entrepreneurs don't become successful because of having a good idea. They become successful because of having a good idea that is executed well.