---
title: 'Poor finishing is worse than not getting started'
author: '{{< var author >}}'
date: '2024-07-22'
---

Getting started is the main thing most people complain about when undertaking a project. Intellectually, they may understand the significance of that project but somehow or other, actually doing it takes a lot of effort. Yet one thing we all know for sure is that:

> You cannot finish until you start.

But an even worse problem is poor finishing, i.e. starting a project only to lose the energy and interest in the way and therefore poorly finishing it.

When you’re in the early stages of working on a project your enthusiasm and energy are almost off the charts. But as time passes, your energy and enthusiasm usually deteriorate, and you lose the desire to complete the project.

Under such circumstances, most people do a half-assed job just so they can mark the project as complete. This is worse than not getting started. Why? Because you'll have wasted your time working on the project only to end up doing a sub-par job.

Whenever you undertake a project, you must maintain the same energy you had when you started. Always tell yourself:

> If you're going to spend time on something, you might as well do a great job at it.

That’s the attitude that will prevent you from poorly finishing your projects.