---
title: "Do something or make an excuse"
author: "Joram Mutenge"
date: "2024-06-10"
---

We each live our own lives and we like different things. We also encounter different opportunities and the way we prioritize those opportunities differs. What ranks high on my list might be at the bottom of your list.

Despite all these differences, we all face this dilemma: should you act on the opportunity or make an excuse not to act on it?

What are some of the opportunities you allowed to pass you by because you made an excuse not to act on them?

It's worth realizing that no one will ever make you go after something or act on an opportunity because even if they did, the final decision comes down to you. Are you going to act or are you going to make an excuse not to act? Excuses stink. No one likes them. Yet people never tire of giving them.

> Failing may be painful but the regret that comes with not trying is twice as painful.

Never let an opportunity slip through your fingers. Always act on any opportunity that comes your way. You don’t know what you can accomplish until you try.

Of course, I'm merely giving words of encouragement. The choice to do something or make an excuse is all yours.