---
title: "Don’t follow your passion"
author: "Joram Mutenge"
date: "2024-06-03"
---

When picking a career, the most common advice is to follow your passion. Unfortunately, passion isn't enough to make a living.

> A dose of idealism is good, but only a dose. To survive, you need to be practical.

While it might be your passion to major in English or Art History, you have to face the reality that the job market in those fields is scarce.

The advice to follow your passion creeps up in business conversations as well. If you asked what business to start, most people would tell you to build a business around something you're passionate about.

This is good advice if the market values your passion. Unfortunately, many things that most people are passionate about aren't valued by the market. They are good hobbies but bad businesses.

> Your business doesn’t need to start from your passion; it can develop into your passion. Almost every business done diligently and successfully will arouse passion in you.

Remember, most people didn't love what they do, they learned to love what they do.