---
title: 'Busy people get things done'
author: '{{< var author >}}'
date: '2024-07-14'
---

> If you want something done then go, if not then send.

The surest way to do something is to do it yourself. But let's be honest, you can't do everything by yourself.

The second-best way to have something done is to give it to a busy person. This may seem counterintuitive. Why on earth would you give a task to someone busy and expect it to be done? Shouldn't you give it to a person who has free time?

When you have too much free time, it means you aren't getting things done. Think about it, productive people are, by nature, busy people. When you're busy, it means you're getting things done. Busy people always look forward to the next project they have to do hence they have little or no free time.

On the other hand, procrastinators tend to have a lot of free time at their disposal because they put off too many projects. They always anticipate having those projects done later, but that time never seems to come.

That's why when you give a busy person something to do, you have a better chance of it being done. Unproductive people have too much free time. When you give them one of your projects to work on, they might just put it on a pile of unfinished projects they are yet to finish someday. But as the saying goes:

> Someday is not among the seven days of the week.