---
title: "Be hard on ideas and soft on people"
author: "Joram Mutenge"
date: "2024-06-02"
---

Running a business is challenging because it involves managing the business’s affairs and managing people.

It's easier to deal with matters related to the business. If you know the ins and outs of your business, you can put systems in place and it will operate perfectly well.

It's not the case with employees because every person is a special case. General systems and procedures do not work well with humans.

Employers and employees need to challenge each other. As an employer, the way you treat your workers can have a serious effect on their productivity.

But challenging them the right way isn’t easy because you can come across as mean. Or your workers might think you're being hard on them.

> The best way to challenge your workers is to be tough on their ideas and opinions but soft on them as individuals.

Let's say a worker proposes an idea you think is lousy, rather than saying "How can you be so stupid as to propose such a terrible idea," you should say, "I don't think that idea is great, and here's why..."

When expressed this way, the worker will know that the objection isn't a personal attack on her but her idea. Moreover, being hard on a person's idea doesn't affect their confidence.

By contrast, being hard on the person drains that person's confidence. The worker may even give up on giving reasons for why the idea is great.

To get the most out of your employees, you must challenge them but you must challenge them well. Criticize the ideas, not the person presenting the idea.