---
title: 'Should you have a business partner?'
author: '{{< var author >}}'
date: '2024-07-21'
categories: [business]
---

While the idea of running a business by yourself and pocketing all the profits in your big fat pockets sounds appealing, it's worth noting that such an endeavor is more likely to work in theory than in practice.

Running a business involves multiple functions that demand someone's attention. You can’t be the only person to take on these functions and execute them successfully. That's why you need a business partner.

But what sort of business partner should you have? The best advice I've received is to not partner with someone who shares the same strengths as you. Unlike in a romantic relationship where you want a partner who is, in many ways, similar to you, in a business relationship, you want a partner who is different from you -- one who is stronger in areas you're weak.

For example, if you're good at sales, partner with someone good at finance -- someone with a feeling for numbers and a great understanding of spreadsheets. You want someone who complements your skills.

> When choosing a business partner, your rule of thumb should be: if they're good at what you are not, then you need them.

The classic mistake when choosing a partner is to go for a friend. If friendship is the only reason you partner with that person, I suggest you look for someone else. I would go as far as to say you don't even have to like your business partner; you just need to notice that they are stronger in areas you are weak.