---
title: "Make work your friend"
author: "Joram Mutenge"
date: "2024-05-31"
categories: [book]
---



In the modern world, working is part of survival. To put food on your table, you have to work.

The challenge is that most people don't enjoy the work they do. Many factors contribute to this including low pay and interest misalignment.

It's hard to be happy at your job when you're underpaid. And it's almost impossible to enjoy your work if you don't find it interesting.

So the best combination is doing interesting work that pays more. How then can you find this type of work?

Naval Ravikant explains work as:

> Doing something that feels like play to you, but looks like work to others.

We all enjoy playing, so when your work feels like play, you'll enjoy it. But the second piece is the most important. Whatever you're doing has to be seen as work by other people. It's what ensures that you're paid for doing it.

When you enjoy your work, you try different things and learn new things. With enhanced knowledge of your job, you become better at it. This in turn increases your earnings.

Put another way, you have to make work your friend. As George Horace Lorimer writes in *More Letters from a Self-Made Merchant to His Son*:

> After forty years of close acquaintance with it, I've found that work is kind to its friends and harsh to its enemies. It pays the fellow who dislikes it his exact wages, and they're generally pretty small; but it gives the man who shines up to it all the money he wants and throws in a heap of fun and satisfaction for good measure.

To be an expert at your work, you have to find it interesting.

When you become an expert, you get paid more.

So, make your work your friend, not your enemy.