---
title: "Other people think your beliefs are silly"
author: "Joram Mutenge"
date: "2024-06-07"
categories: [tv show]
---

The other day, I watched the TV show *The Americans* and it made me think about the beliefs we hold on to in our lives.

It's funny that other people might consider your beliefs ridiculous or unimportant and you might think of their beliefs the same way.

In the show, the lead characters Philip and Elizabeth Jennings strongly believe communism is the best way to run societies and are willing to die for that belief. Watching the behavior of these two characters reminded me of Albert Camus’ saying:

> There are causes worth dying for, but none worth killing for.

Philip and Elizabeth aren’t just willing to die for their belief in communism. They go further than that and kill people for it.

I was especially shocked by their reaction when their daughter Paige started attending a church youth group. They didn’t want her to be religious. To them believing in God was silly and they couldn't stand seeing their daughter participate in this silliness. When Paige started praying before dinner, they thought her religious flirtations had gone too far.

The experience made me reflect on my own beliefs. Yes, they make sense to me, but do they also make sense to others? Do other people think my beliefs are silly, just like I’m inclined to think theirs are?

When you believe in something, you’re convinced it contains truth, but that truth may not be evident to people who don’t share that belief.

Philip and Elizabeth are so indoctrinated in the communist ideology that they can't fathom that there might be a better way to run a society. Elizabeth even reminds her KGB colleague that communism was the path to:

> A world without exploitation and dignity for all.

Here’s an interesting exercise for you. Try looking at your beliefs as an impartial outsider. Do they still make sense? Do they seem silly — ridiculous even? Let me know.